chore: create layout component (WEB-40)
dallassoftwaredevelopers/DSDsite pull request #88
Opened 2024-04-29 18:25 UTC by climaxmba

# chore: create layout component (WEB-40): #86 
> ## _In progress..._

2024-04-29 19:01 UTC, climaxmba commented on src/app/components/layout/layout.tsx
> +    </>
Good day @GetBlackBoxSolutions! Please I need to know if this component should return a `<div>` as the root element or is it alright this: `<>{ children }</>`

2024-05-02 23:23 UTC, GetBlackBoxSolutions requested changes
This is very close. Please look at the NextJs documentation. 

https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts#layout-pattern

2024-05-03 19:19 UTC, climaxmba commented
> This is very close. Please look at the NextJs documentation.
> 
> https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts#layout-pattern

I have added the `children` prop and nested `children` in `<main>`. By the way, would it be ok if I added a test for the component?

2024-05-07 00:08 UTC, GetBlackBoxSolutions approved these changes

2024-05-07 00:08 UTC, merged