chore: create a footer according to the Figma design (WEB-42) #90
dallassoftwaredevelopers/DSDsite pull request #93
Opened 2024-05-15 22:20 UTC by Nur4ck

Preview: 
Desktop
![grafik](https://github.com/dallassoftwaredevelopers/DSDsite/assets/144545225/0bd2ce7b-3d7d-41a6-b9d2-8be7036da87d)
Mobile
![grafik](https://github.com/dallassoftwaredevelopers/DSDsite/assets/144545225/3f8aee3c-13ea-4ec7-bd08-f4d3b8c55071)

I have also modified the Sociallinks.tsx so that the component can be adjusted more easily in the footer and also in future components.

2024-05-20 21:40 UTC, GetBlackBoxSolutions requested changes

2024-05-20 21:40 UTC, GetBlackBoxSolutions commented on src/app/components/footer/footer.tsx
Can you please move the const variables outside of the function?

2024-05-21 10:30 UTC, Nur4ck commented on src/app/components/footer/footer.tsx
Sure.

2024-05-21 10:54 UTC, Nur4ck commented on src/app/components/footer/footer.tsx
I have outsourced the constants into the footerSocialdata.tsx file.

2024-05-21 15:47 UTC, GetBlackBoxSolutions approved these changes

2024-05-21 15:47 UTC, merged